package service

import (
	"encoding/hex"
	"regexp"
	"testing"

	"cciicc/types"
)

func TestRandomSpaceIdGeneratorFormat(t *testing.T) {
	spaces := types.GetInstance_spaces()
	// Clear any existing spaces to avoid side effects
	*spaces = types.Spaces{}

	pattern := `^[a-z][0-9]{1,3}$`
	re := regexp.MustCompile(pattern)

	for i := 0; i < 100; i++ {
		id := Random_space_id_generator()
		if !re.MatchString(id) {
			t.Errorf("Generated ID %s does not match expected format %s", id, pattern)
		}
	}
}

func TestRandomSpaceIdGeneratorCollision(t *testing.T) {
	spaces := types.GetInstance_spaces()

	// Clear any existing spaces
	*spaces = types.Spaces{}

	// Generate some IDs and add them to spaces
	existingIDs := make(map[string]bool)
	for i := 0; i < 100; i++ {
		id := Random_space_id_generator()
		existingIDs[id] = true
		*spaces = append(*spaces, types.Space{Sp_id: id})
	}

	// Generate a new ID and verify it does not collide with any existing ones
	for i := 0; i < 100; i++ {
		newID := Random_space_id_generator()
		if existingIDs[newID] {
			t.Errorf("Generated ID %s collided with existing ID in spaces", newID)
		}
		// Add to spaces to continue testing collision
		existingIDs[newID] = true
		*spaces = append(*spaces, types.Space{Sp_id: newID})
	}

	// Clean up
	*spaces = types.Spaces{}
}

func TestRandomSessionkeyGeneratorFormat(t *testing.T) {
	users := types.GetInstance_users()
	*users = types.Users{}

	space_id := "testspace"
	key := Random_sessionkey_generator(space_id)

	// 16 bytes encoded in hex is exactly 32 characters long
	if len(key) != 32 {
		t.Errorf("Expected session key length 32, got %d", len(key))
	}

	matched, _ := regexp.MatchString("^[0-9a-f]{32}$", key)
	if !matched {
		t.Errorf("Generated session key %s is not a valid hex string", key)
	}
}

func TestRandomSessionkeyGeneratorCollision(t *testing.T) {
	// Setup custom rand bytes function to force collision
	originalGenerateRandomBytes := generateRandomBytes
	defer func() {
		generateRandomBytes = originalGenerateRandomBytes
	}()

	users := types.GetInstance_users()
	*users = types.Users{}

	space_id := "testspace"

	// Mock sequence of generated bytes
	// 1: bytes for "test1"
	// 2: bytes for "test1" (collision)
	// 3: bytes for "test2" (valid)
	test1Bytes := make([]byte, 16)
	test1Bytes[0] = 1
	test2Bytes := make([]byte, 16)
	test2Bytes[0] = 2

	seq := [][]byte{test1Bytes, test1Bytes, test2Bytes}
	idx := 0
	generateRandomBytes = func(n int) ([]byte, error) {
		if idx < len(seq) {
			val := seq[idx]
			idx++
			return val, nil
		}
		return make([]byte, n), nil // fallback
	}

	// Set up collision condition
	// 1st generated hex key from test1Bytes
	test1Hex := hex.EncodeToString(test1Bytes)
	*users = append(*users, types.User{User_sessionkey: test1Hex})

	key := Random_sessionkey_generator(space_id)

	// verify that idx advanced to 3 (meaning it called generateRandomBytes 3 times: initial + 2 collisions checked)
	if idx != 3 {
		t.Errorf("Expected generateRandomBytes to be called 3 times, got %d", idx)
	}

	// Verify the final key generated is from test2Bytes
	expectedKey := hex.EncodeToString(test2Bytes)

	if key != expectedKey {
		t.Errorf("Expected session key %s, got %s", expectedKey, key)
	}
}
